baseURL = 'https:www.jsulz.com/'
languageCode = 'en-us'
title = 'jsulz'
theme = 'beautifulhugo'
DefaultContentLanguage = "en"
enableRobotsTXT = true
contentDir = "content"

[Params]
subtitle = "Fueled by coffee, code, and spreadsheets"
mainSections = ["post", "posts"]
#logo = "img/avatar-icon.png" # Expecting square dimensions
dateFormat = "January 2, 2006"
#commit = false
rss = true
#comments = true
#readingTime = true
#wordCount = true
useHLJS = true
#socialShare = true
#delayDisqus = true
#showRelatedPosts = true
favicon = "img/favicon.ico"
since = 2016
homeTitle = 'jsulz'

[Author]
# Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
name = "Jared Sulzdorf"
website = "/"
email = "j.sulzdorf@gmail.com"
github = "jsulz"
linkedin = "jaredsulzdorf"


[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2
